// <auto-generated />
using System;
using BibliotecaEscolar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace BibliotecaEscolar.Data.Migrations
{
    [DbContext(typeof(BibliotecaDbContext))]
    [Migration("20260809031148_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliotecaEscolar.Models.Bibliotecario", b =>
                {
                    b.Property<int>("IdBibliotecario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_BIBLIOTECARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBibliotecario"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.HasKey("IdBibliotecario");

                    b.HasIndex("CodigoEmpleado")
                        .IsUnique()
                        .HasDatabaseName("UX_BIBLIOTECARIOS_CODIGO");

                    b.ToTable("BIBLIOTECARIOS", (string)null);
                });

            modelBuilder.Entity("BibliotecaEscolar.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CATEGORIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("IdCategoria");

                    b.ToTable("CATEGORIAS", (string)null);
                });

            modelBuilder.Entity("BibliotecaEscolar.Models.Libro", b =>
                {
                    b.Property<int>("IdLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LIBRO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLibro"));

                    b.Property<int>("AnioPublicacion")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CATEGORIA");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("IdLibro");

                    b.HasIndex("ISBN")
                        .IsUnique()
                        .HasDatabaseName("UX_LIBROS_ISBN");

                    b.HasIndex("IdCategoria");

                    b.ToTable("LIBROS", (string)null);
                });

            modelBuilder.Entity("BibliotecaEscolar.Models.Prestamo", b =>
                {
                    b.Property<int>("IdPrestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PRESTAMO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrestamo"));

                    b.Property<bool>("Devuelto")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IdBibliotecario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_BIBLIOTECARIO");

                    b.Property<int>("IdLibro")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LIBRO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("IdPrestamo");

                    b.HasIndex("IdBibliotecario");

                    b.HasIndex("IdLibro");

                    b.HasIndex("IdUsuario");

                    b.ToTable("PRESTAMOS", (string)null);
                });

            modelBuilder.Entity("BibliotecaEscolar.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Matricula")
                        .IsUnique()
                        .HasDatabaseName("UX_USUARIOS_MATRICULA");

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("BibliotecaEscolar.Models.Libro", b =>
                {
                    b.HasOne("BibliotecaEscolar.Models.Categoria", "Categoria")
                        .WithMany("Libros")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("BibliotecaEscolar.Models.Prestamo", b =>
                {
                    b.HasOne("BibliotecaEscolar.Models.Bibliotecario", "Bibliotecario")
                        .WithMany("Prestamos")
                        .HasForeignKey("IdBibliotecario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliotecaEscolar.Models.Libro", "Libro")
                        .WithMany("Prestamos")
                        .HasForeignKey("IdLibro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliotecaEscolar.Models.Usuario", "Usuario")
                        .WithMany("Prestamos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bibliotecario");

                    b.Navigation("Libro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BibliotecaEscolar.Models.Bibliotecario", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("BibliotecaEscolar.Models.Categoria", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("BibliotecaEscolar.Models.Libro", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("BibliotecaEscolar.Models.Usuario", b =>
                {
                    b.Navigation("Prestamos");
                });
#pragma warning restore 612, 618
        }
    }
}
