using BibliotecaEscolar.Data; using BibliotecaEscolar.Models; using BibliotecaEscolar.Services; using Microsoft.EntityFrameworkCore;
namespace BibliotecaEscolar;
public class FrmLibros : Form
{
    private readonly BibliotecaDbContext _context=new();private readonly LibroService _service;private readonly DataGridView _grid;private readonly TextBox _titulo,_autor,_isbn,_anio;private readonly ComboBox _categoria;private readonly CheckBox _disponible;private int? _id;
    public FrmLibros(){_service=new(_context);var ui=FormHelper.CrearEstructura(this,"Gestión de Libros");_grid=ui.grid;_titulo=FormHelper.Campo(ui.editor,"Título",15,10,220);_autor=FormHelper.Campo(ui.editor,"Autor",250,10,180);_isbn=FormHelper.Campo(ui.editor,"ISBN",445,10,140);_anio=FormHelper.Campo(ui.editor,"Año",600,10,80);_categoria=FormHelper.Combo(ui.editor,"Categoría",695,10,210);_disponible=new CheckBox{Text="Disponible",Location=new Point(15,85),Checked=true};ui.editor.Controls.Add(_disponible);
        FormHelper.Boton(ui.buttons,"Nuevo / Limpiar",(_,_)=>Limpiar());FormHelper.Boton(ui.buttons,"Guardar",Guardar);FormHelper.Boton(ui.buttons,"Editar selección",Editar);FormHelper.Boton(ui.buttons,"Eliminar",Eliminar,true);FormHelper.Boton(ui.buttons,"Cerrar",(_,_)=>Close());Load+=async(_,_)=>await Cargar();}
    private async Task Cargar(){try{var cats=await _context.Categorias.AsNoTracking().OrderBy(x=>x.Nombre).ToListAsync();_categoria.DataSource=cats;_categoria.DisplayMember=nameof(Categoria.Nombre);_categoria.ValueMember=nameof(Categoria.IdCategoria);_grid.DataSource=await _service.ListarAsync();foreach(string n in new[]{nameof(Libro.Categoria),nameof(Libro.Prestamos)})if(_grid.Columns[n] is DataGridViewColumn c)c.Visible=false;Limpiar();}catch(Exception ex){FormHelper.Error("Libros",ex);}}
    private async void Guardar(object?s,EventArgs e){try{if(!int.TryParse(_anio.Text,out int anio))throw new ArgumentException("El año de publicación debe ser válido.");if(_categoria.SelectedValue is not int cat)throw new ArgumentException("Seleccione una categoría.");if(_id.HasValue)await _service.ModificarAsync(_id.Value,_titulo.Text,_autor.Text,_isbn.Text,anio,_disponible.Checked,cat);else await _service.CrearAsync(_titulo.Text,_autor.Text,_isbn.Text,anio,_disponible.Checked,cat);MessageBox.Show("Libro guardado correctamente.");await Cargar();}catch(Exception ex){FormHelper.Error("Libros",ex);}}
    private async void Editar(object?s,EventArgs e){if(_grid.CurrentRow?.DataBoundItem is not Libro x){MessageBox.Show("Seleccione un libro.");return;}try{var i=await _service.BuscarPorIdAsync(x.IdLibro)??throw new KeyNotFoundException("El libro ya no existe.");_id=i.IdLibro;_titulo.Text=i.Titulo;_autor.Text=i.Autor;_isbn.Text=i.ISBN;_anio.Text=i.AnioPublicacion.ToString();_disponible.Checked=i.Disponible;_categoria.SelectedValue=i.IdCategoria;}catch(Exception ex){FormHelper.Error("Libros",ex);}}
    private async void Eliminar(object?s,EventArgs e){if(_grid.CurrentRow?.DataBoundItem is not Libro x){MessageBox.Show("Seleccione un libro.");return;}if(MessageBox.Show("¿Eliminar el libro seleccionado?","Confirmar",MessageBoxButtons.YesNo)!=DialogResult.Yes)return;try{MessageBox.Show(await _service.EliminarAsync(x.IdLibro));await Cargar();}catch(Exception ex){FormHelper.Error("Libros",ex);}}
    private void Limpiar(){_id=null;_titulo.Clear();_autor.Clear();_isbn.Clear();_anio.Clear();_disponible.Checked=true;if(_categoria.Items.Count>0)_categoria.SelectedIndex=0;_grid.ClearSelection();}protected override void OnFormClosed(FormClosedEventArgs e){_context.Dispose();base.OnFormClosed(e);}
}
