using BibliotecaEscolar.Data; using BibliotecaEscolar.Services; using Microsoft.EntityFrameworkCore;
namespace BibliotecaEscolar;
public class FrmPrestamos : Form
{
    private readonly BibliotecaDbContext _context=new();private readonly PrestamoService _service;private readonly DataGridView _grid;private readonly ComboBox _usuario,_libro,_bibliotecario;private readonly DateTimePicker _fecha;
    public FrmPrestamos(){_service=new(_context);var ui=FormHelper.CrearEstructura(this,"Gestión de Préstamos");_grid=ui.grid;_usuario=FormHelper.Combo(ui.editor,"Usuario",15,12,260);_libro=FormHelper.Combo(ui.editor,"Libro disponible",290,12,260);_bibliotecario=FormHelper.Combo(ui.editor,"Bibliotecario",565,12,260);ui.editor.Controls.Add(new Label{Text="Fecha",Location=new Point(15,82),AutoSize=true});_fecha=new DateTimePicker{Location=new Point(65,78),Width=210};ui.editor.Controls.Add(_fecha);FormHelper.Boton(ui.buttons,"Registrar préstamo",Registrar);FormHelper.Boton(ui.buttons,"Registrar devolución",Devolver);FormHelper.Boton(ui.buttons,"Actualizar",async(_,_)=>await Cargar());FormHelper.Boton(ui.buttons,"Cerrar",(_,_)=>Close());Load+=async(_,_)=>await Cargar();}
    private async Task Cargar(){try{var usuarios=await _context.Usuarios.AsNoTracking().OrderBy(x=>x.Apellidos).ToListAsync();_usuario.DataSource=usuarios.Select(x=>new Opcion(x.IdUsuario,$"{x.Nombre} {x.Apellidos} - {x.Matricula}")).ToList();var libros=await _context.Libros.AsNoTracking().Where(x=>x.Disponible).OrderBy(x=>x.Titulo).ToListAsync();_libro.DataSource=libros.Select(x=>new Opcion(x.IdLibro,$"{x.Titulo} - {x.ISBN}")).ToList();var bibliotecarios=await _context.Bibliotecarios.AsNoTracking().OrderBy(x=>x.Apellidos).ToListAsync();_bibliotecario.DataSource=bibliotecarios.Select(x=>new Opcion(x.IdBibliotecario,$"{x.Nombre} {x.Apellidos} - {x.CodigoEmpleado}")).ToList();foreach(var combo in new[]{_usuario,_libro,_bibliotecario}){combo.DisplayMember=nameof(Opcion.Texto);combo.ValueMember=nameof(Opcion.Id);}var prestamos=await _service.ListarAsync();_grid.DataSource=prestamos.Select(x=>new FilaPrestamo(x.IdPrestamo,$"{x.Usuario.Nombre} {x.Usuario.Apellidos}",x.Libro.Titulo,$"{x.Bibliotecario.Nombre} {x.Bibliotecario.Apellidos}",x.FechaPrestamo,x.FechaDevolucion,x.Devuelto?"Devuelto":"Pendiente")).ToList();_grid.ClearSelection();}catch(Exception ex){FormHelper.Error("Préstamos",ex);}}
    private async void Registrar(object?s,EventArgs e){try{if(_usuario.SelectedValue is not int u||_libro.SelectedValue is not int l||_bibliotecario.SelectedValue is not int b)throw new ArgumentException("Seleccione usuario, libro y bibliotecario.");await _service.CrearAsync(u,l,b,_fecha.Value);MessageBox.Show("Préstamo registrado correctamente.");await Cargar();}catch(Exception ex){FormHelper.Error("Préstamos",ex);}}
    private async void Devolver(object?s,EventArgs e){if(_grid.CurrentRow?.DataBoundItem is not FilaPrestamo x){MessageBox.Show("Seleccione un préstamo.");return;}if(x.Estado=="Devuelto"){MessageBox.Show("El préstamo ya fue devuelto.");return;}try{MessageBox.Show(await _service.RegistrarDevolucionAsync(x.IdPrestamo,_fecha.Value));await Cargar();}catch(Exception ex){FormHelper.Error("Préstamos",ex);}}
    protected override void OnFormClosed(FormClosedEventArgs e){_context.Dispose();base.OnFormClosed(e);}private sealed record Opcion(int Id,string Texto);private sealed record FilaPrestamo(int IdPrestamo,string Usuario,string Libro,string Bibliotecario,DateTime FechaPrestamo,DateTime? FechaDevolucion,string Estado);
}
